# NOTE: Docker Compose 通常用于管理持久层容器，例如：MySQL、Redis、MongoDB 等
version: '3.9'

services:
  # ！MySQL 容器配置
  mysql:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: system-dorm
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      # - mysql_data:/var/lib/mysql
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend
# 卷配置，如果使用了卷，需要允许外部访问
volumes:
  mysql-data:
    driver: local

# 网络配置
networks:
  backend:
    driver: bridge
